### PR TITLE
Ansible support to multiple distros

### PR DESCRIPTION
**Pull request by willianpaixao**
See #389

### CODE REVIEW

**Comment by onedr0p** [comment]
I think there's more to do than just this. You'll need to conditionally check fedora and Ubuntu on more things like.. selinux

**Comment by onedr0p** [comment]
Closing this issue, I am still open to PRs but they need to be more complete than this.

**Comment by willianpaixao** [comment]
Hi @onedr0p, I'd like to finish this feature. Could you please reopen this PR?

**Comment by onedr0p** [comment]
image

You will have to open a new PR it seems.

**Pull request closed without merging**
