### PR TITLE
Add option to disable kube-vip (part 2)

### PR DESCRIPTION
**Pull request by mrueg**
**Description of the change**

Allow disabling kube-vip, the previous PR missed to include the ansible changes.

### CODE REVIEW

**Review by onedr0p — APPROVED** [review]

**Comment by onedr0p** [comment]
I run into someone who had kube-vip enabled in the settings but it was not deployed with Ansible. Not sure if we should revert these PRs or not

**Comment by onedr0p** [comment]
Discord ref: https://discord.com/channels/673534664354430999/995235505178427392/995235508408029276

**Comment by mrueg** [comment]
@onedr0p I'm not on discord, so I can't see what is going on there. If I'd had to guess and I'd say that the config.env file is not updated and does not include BOOTSTRAP_KUBE_VIP_ENABLED=true

**Comment by onedr0p** [comment]
The issue was an outdated version of yq

**Pull request merged**
